syntax="proto3";

package chat.v1;

option go_package = "github.com/kaelorin/chat";

message Text {
  string content = 1;
}

message Attachment {
  string             name          = 1;
  int64              size          = 2;
  string             content_type  = 3;
  map<string,string> user_metadata = 4;
}

message Part {
  string type = 1;
  oneof content {
    Text       text       = 2;
    Attachment attachment = 3;
  }
  int32 position = 4;
}

message SendMessageTextRequest {
  string          sender_id           = 1;
  string          conversation_id     = 2;
  optional string reply_to_message_id = 3;
  repeated Part   parts               = 4;
}

message SendMessageTextResponse {
  string conversation_id = 1;
  string message_id      = 2;
  string state           = 3;
}

message SendMessageWithAttachmentRequest {
  string          sender_id           = 1;
  string          conversation_id     = 2;
  optional string reply_to_message_id = 3;
  repeated Part   parts               = 4;
}

message SendMessageWithAttachmentPart {
  string          id    = 1;
  string          type  = 2;
  optional string text  = 3;
  optional string token = 4;

}

message SendMessageWithAttachmentResponse {
  string                                 conversation_id = 1;
  string                                 message_id      = 2;
  string                                 state           = 3;
  repeated SendMessageWithAttachmentPart parts           = 4;
}