syntax="proto3";

package otp.v1;

option go_package="github.com/Newcode05/contracts/otp/v1;otp";

import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";

enum ErrorCode {
  ERROR_CODE_UNSPECIFIED = 0;
  MAX_ATTEMPT_EXCEEDED   = 1;
  MAX_RESEND_EXCEEDED    = 2;
  OTP_INVALID            = 3;
  SESSION_INVALID        = 4;
  INTERNAL_SERVER        = 5;
  COOLDOWN_ACTIVE        = 6;
  LOCKED                 = 7;
}

message ErrorDetail {
  ErrorCode                 Code           = 1;
  google.protobuf.Timestamp cooldown_until = 2;
  google.protobuf.Timestamp lock_until     = 3;

  int32 remaining_attempts = 4;
  int32 remaining_resends  = 5;
}