syntax="proto3";
package media.v1;

option go_package = "github.com/kaelrion/contracts/media/v1;media";

import "media/v1/type.proto";

service Service {
  rpc InitializeMultipartUploads(InitializeUploadsRequest)returns (InitializeUploadsResponse);
  rpc SignUploadParts(SignUploadPartsRequest)returns (SignUploadPartsResponse);
  rpc CompleteMultipartUploads(CompleteMultipartUploadRequest)returns (CompleteMultipartUploadResponse);
  rpc PresignDownloads(PresignDownloadsRequest)returns (PresignDownloadsResponse);
}