syntax="proto3";

package user.v1;

option go_package = "github.com/kaelrion/contracts/gen/user/v1;user";
import "google/protobuf/timestamp.proto";
message GetProfileRequest {
  string principal_id = 1;
}

message GetProfileResponse {
  string                             name                = 1;
  string                             display_name        = 2;
  optional string                    bio                 = 3;
  optional string                    avatar_media_id     = 4;
  optional string                    background_media_id = 5;
  optional google.protobuf.Timestamp birthday            = 6;
}

message InitializeUploadAvatarRequest {
  string principal_id = 1;
  string content_type = 2;
  int64  size         = 3;
}

message InitializeUploadAvatarResponse {
  string token    = 1;
  string media_id = 2;
}

message CompleteUploadAvatarRequest {
  string principal_id = 1;
  string media_id     = 2;
}

message CompleteUploadAvatarResponse {
  string url = 1;
}