syntax="proto3";

package user.v1;

option go_package = "github.com/kaelrion/contracts/gen/user/v1;user";
import "google/protobuf/timestamp.proto";
message GetProfileRequest {
  string principal_id = 1;
}

message GetProfileResponse {
  string                             name           = 1;
  string                             display_name   = 2;
  optional string                    bio            = 3;
  optional string                    avatar_url     = 4;
  optional string                    background_url = 5;
  optional google.protobuf.Timestamp birthday       = 6;
}

message PresignUpdateAvatarRequest {
  string principal_id = 1;
  string content_type = 2;
  int64  size         = 3;
}

message PresignUpdateAvatarResponse {
  string token = 1;
}
